/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TH1_Bai1;




import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import static java.lang.System.exit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author er1nzz
 */
public class Bai1 extends javax.swing.JFrame {

    
    ArrayList<SVTT> tt = new ArrayList();
    ArrayList<SVMM> mm = new ArrayList();
    String header[] = {"Mã SV","Họ Tên","Ngày sinh","Điểm trung bình","Lương","Học phí"};
    DefaultTableModel model = new DefaultTableModel(header,0);
    
    
    
    public Bai1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        tblResult.setModel(model);
        txtSalary.setEnabled(false);
        txtFee.setEnabled(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFee = new javax.swing.JTextField();
        radSVTT = new javax.swing.JRadioButton();
        radSVMM = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cbSex = new javax.swing.JComboBox<>();
        txtScore = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã SV");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 59, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 63, 316, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ngày sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 147, -1, -1));

        txtBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthdayActionPerformed(evt);
            }
        });
        getContentPane().add(txtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 147, 316, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Lương");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 318, 316, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Học phí");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 353, 316, -1));

        buttonGroup1.add(radSVTT);
        radSVTT.setLabel("SVTT");
        radSVTT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radSVTTStateChanged(evt);
            }
        });
        radSVTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSVTTActionPerformed(evt);
            }
        });
        getContentPane().add(radSVTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 273, -1, -1));

        buttonGroup1.add(radSVMM);
        radSVMM.setLabel("SVMM");
        radSVMM.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radSVMMStateChanged(evt);
            }
        });
        radSVMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSVMMActionPerformed(evt);
            }
        });
        getContentPane().add(radSVMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 273, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Giới tính");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 235, -1, -1));

        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexActionPerformed(evt);
            }
        });
        getContentPane().add(cbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 235, 83, -1));

        txtScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScoreActionPerformed(evt);
            }
        });
        getContentPane().add(txtScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 192, 316, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Điểm");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 187, -1, -1));

        btnInput.setText("Nhập");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 406, 99, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 406, 100, -1));

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 406, 90, -1));

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 406, 90, -1));

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 37, 505, 402));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Họ tên");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 103, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 107, 316, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TH1_Bai1/03_gettyimages-165604758_resized.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1140, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthdayActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeeActionPerformed

    private void radSVTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSVTTActionPerformed
        txtFee.setEnabled(true);
        txtFee.setText("");
        txtSalary.setText("");
        txtSalary.setEnabled(false);
    }//GEN-LAST:event_radSVTTActionPerformed

    private void txtScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScoreActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:if(radMM.isSelected())
        if(radSVMM.isSelected()){
            try {
                FileOutputStream fos = new FileOutputStream("svmatma.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(mm);

                JOptionPane.showMessageDialog(rootPane, "Lưu thành công dánh sách sinh viên Mật Mã");
                oos.close();
                fos.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else if (radSVTT.isSelected())
      {
          try {
              FileOutputStream fos=new FileOutputStream("svhtn.txt");
              OutputStreamWriter osw=new OutputStreamWriter(fos);
              BufferedWriter bw =new BufferedWriter(osw);
              
              for(SVTT t:tt)
              {
                  String line = "";
                  line+=t.getID()+"$";
                  line+=t.getName()+"$";
                  line+=new SimpleDateFormat().format(t.getBirthday())+ "$";
                  line+=t.getSex()+ "$";
                  line+=t.getScore()+ "$";
                  line+=t.getFee()+ "$";
                  bw.write(line);
                  bw.newLine();
              }
              bw.close();
              fos.close();
              osw.close();
          JOptionPane.showMessageDialog(rootPane, "Lưu thành công danh sách sinh viên Thông Thường");
          } catch (Exception e) {
          }
      }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void cbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexActionPerformed

    private void radSVTTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radSVTTStateChanged
        
    }//GEN-LAST:event_radSVTTStateChanged

    private void radSVMMStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radSVMMStateChanged
        
    }//GEN-LAST:event_radSVMMStateChanged

    private void radSVMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSVMMActionPerformed
        txtFee.setEnabled(false);
        txtSalary.setEnabled(true);
        txtSalary.setText("");
        txtFee.setText("");
    }//GEN-LAST:event_radSVMMActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtID.setText("");
        txtName.setText("");
        txtBirthday.setText("");
        cbSex.setSelectedItem("Nam");
        txtFee.setText("");
        txtSalary.setText("");
        txtScore.setText("");
        buttonGroup1.clearSelection();
        txtSalary.setEnabled(false);
        txtFee.setEnabled(false);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        String empty="";
        if ((txtID.getText().equals(empty))||(txtName.getText().equals(empty)) ||(txtBirthday.getText().equals(empty)) ||(txtScore.getText().equals(empty)) ){
            JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ thông tin!");
        }
        if (radSVMM.isSelected()){
            SVMM m =new SVMM();
            m.setID(txtID.getText());
            m.setName(txtName.getText());
            m.setSex(cbSex.getSelectedItem().toString());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                m.setBirthday(sdf.parse(txtBirthday.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(Bai1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                m.setScore(Float.parseFloat(txtScore.getText()));
                m.setSalary(Float.parseFloat(txtSalary.getText()));} catch (NumberFormatException e) {
            }
            mm.add(m);
            model.addRow(new Object[]{m.getID(), m.getName(), m.getBirthday(), m.getScore(), m.getSalary(), ""});
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công 1 SVMM!");
        }
        else
        if (radSVTT.isSelected()){
            SVTT t = new SVTT();
            t.setID(txtID.getText());
            t.setName(txtName.getText());
            t.setSex(cbSex.getSelectedItem().toString());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                t.setBirthday(sdf.parse(txtBirthday.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(Bai1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                t.setScore(Float.parseFloat(txtScore.getText()));
                t.setFee(Double.parseDouble(txtFee.getText()));
            } catch (NumberFormatException e) {
            }
            tt.add(t);
            System.out.println(t.toString());
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công 1 SVTT!");
            model.addRow(new Object[]{t.getID(), t.getName(), t.getBirthday(), t.getScore(),"",t.getFee()});
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Chọn loại sinh viên!!!");
        }
        
    }//GEN-LAST:event_btnInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radSVMM;
    private javax.swing.JRadioButton radSVTT;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
