/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai3;

import TH1_Bai1.Bai1;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author er1nzz
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    ArrayList<Employee> list = new ArrayList();
    String header[] = {"Họ Tên", "Ngày sinh","Địa chỉ", "Giới tính", "Phòng ban", "Hệ số lương","Thâm niên","Lương cơ bản","Lương"};
    DefaultTableModel model = new DefaultTableModel(header, 0);
    Employee m = new Employee();
    
    public Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        tblResult.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBaseSalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSalaryrRate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSeniority = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnReadFile = new javax.swing.JButton();
        btnWriteFile = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnSalary = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 58, 274, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Quản lý nhân viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Họ tên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));
        getContentPane().add(txtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 96, 274, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày sinh");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 134, 274, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Địa chỉ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới tính");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, -1));

        txtBaseSalary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBaseSalaryFocusLost(evt);
            }
        });
        getContentPane().add(txtBaseSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 321, 274, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lương cơ bản");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, -1, -1));
        getContentPane().add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 207, 274, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phòng ban");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        txtSalaryrRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalaryrRateFocusLost(evt);
            }
        });
        getContentPane().add(txtSalaryrRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 245, 274, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hệ số lương");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        txtSeniority.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeniorityFocusLost(evt);
            }
        });
        getContentPane().add(txtSeniority, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 283, 274, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thâm niên");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, -1, -1));

        buttonGroup1.add(radioMale);
        radioMale.setText("Nam");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        getContentPane().add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 166, -1, -1));

        buttonGroup1.add(radioFemale);
        radioFemale.setText("Nữ");
        getContentPane().add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 166, -1, -1));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 399, -1, -1));

        btnReadFile.setText("Đọc file");
        btnReadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnReadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 399, -1, -1));

        btnWriteFile.setText("Ghi file");
        btnWriteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnWriteFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 399, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 399, -1, -1));

        jScrollPane2.setViewportView(pnSalary);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 359, 274, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lương ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, -1));

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 58, 775, 389));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai3/09_gettyimages-531473846_medium_resized.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMaleActionPerformed

    private void btnReadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadFileActionPerformed
        // TODO add your handling code here:
        ArrayList<Employee> ds = new ArrayList();
        try {
            //FileInputStream fis = new FileInputStream("nhanvien.dat");
            //InputStreamReader isr = new InputStreamReader(fis);
            BufferedReader br = new BufferedReader(new FileReader("nhanvien.dat"));
            String line = "";
            Employee t = new Employee();
            while ((line=br.readLine()) != null) {
                if (line.length() > 0) {
                    String[] result = line.split("\\$",-1);
                    System.out.println(line);
                    t.setName(result[0]);
                    t.setBirthday(result[1]);
                    t.setAddress(result[2]);
                    t.setSex(result[3]);
                    
                    t.setDepartment(result[4]);
                    t.setSalaryrate(Float.parseFloat(result[5]));
                    t.setSeniority(Float.parseFloat(result[6]));
                    t.setBasesalary(Integer.valueOf(result[7]));
                    t.setSalary(Float.parseFloat(result[8]));
                    ds.add(t);
                    model.addRow(new Object[]{t.getName(), t.getBirthday(), t.getSex(), t.getDepartment(), t.getSalaryrate(),t.getSeniority(),t.getBasesalary(),t.getSalary()});
                }
             //   line = br.readLine();
            }
            br.close();
            //isr.close();
            //fis.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReadFileActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtBirthday.setText("");
        txtAddress.setText("");
        buttonGroup1.clearSelection();
        txtDepartment.setText("");
        txtSalaryrRate.setText("");
        txtSeniority.setText("");
        txtBaseSalary.setText("");
        pnSalary.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String empty = "";
        if ((txtAddress.getText().equals(empty)) || (txtName.getText().equals(empty)) || (txtBirthday.getText().equals(empty)) || (txtDepartment.getText().equals(empty))|| (txtSeniority.getText().equals(empty))|| (txtBaseSalary.getText().equals(empty))|| (txtSalaryrRate.getText().equals(empty))) {
            JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ thông tin!");
        }
        
        m.setName(txtName.getText());
        m.setAddress(txtAddress.getText());
        if (radioFemale.isSelected()){
            m.setSex("Nữ");
        }
        else
        {
            m.setSex("Nam");
        }
        
        m.setBirthday(txtBirthday.getText());
        m.setDepartment(txtDepartment.getText());
        
            m.setSalaryrate(Double.parseDouble(txtSalaryrRate.getText()));
            m.setSeniority(Double.parseDouble(txtSeniority.getText()));
            m.setBasesalary(Integer.parseInt(txtBaseSalary.getText()));
        
        
        System.out.println(m.toString());
        list.add(m);
        int i;
        for (i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).toString());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSalaryrRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalaryrRateFocusLost
        // TODO add your handling code here:
        String empty="";
        if(!(txtSeniority.getText().equals(empty)) && !(txtBaseSalary.getText().equals(empty)) && !(txtSalaryrRate.getText().equals(empty))){
            double r = Double.parseDouble(txtSalaryrRate.getText());
            double s = Double.parseDouble(txtSeniority.getText());
            int b = Integer.parseInt(txtBaseSalary.getText());
            m.setSalary(b*r*(s/100));
            pnSalary.setText(""+m.getSalary());
            
            
        }
    }//GEN-LAST:event_txtSalaryrRateFocusLost

    private void txtSeniorityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeniorityFocusLost
        // TODO add your handling code here:
        String empty = "";
        if (!(txtSeniority.getText().equals(empty)) && !(txtBaseSalary.getText().equals(empty)) && !(txtSalaryrRate.getText().equals(empty))) {
            double r = Double.parseDouble(txtSalaryrRate.getText());
            double s = Double.parseDouble(txtSeniority.getText());
            int b = Integer.parseInt(txtBaseSalary.getText());
            m.setSalary(b * r * (s / 100));
            pnSalary.setText("" + m.getSalary());
            

        }
    }//GEN-LAST:event_txtSeniorityFocusLost

    private void txtBaseSalaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBaseSalaryFocusLost
        // TODO add your handling code here:
        String empty = "";
        if (!(txtSeniority.getText().equals(empty)) && !(txtBaseSalary.getText().equals(empty)) && !(txtSalaryrRate.getText().equals(empty))) {
            float r = Float.parseFloat(txtSalaryrRate.getText());
            float s = Float.parseFloat(txtSeniority.getText());
            int b = Integer.parseInt(txtBaseSalary.getText());
            m.setSalary(b * r * (s / 100));
            pnSalary.setText("" + m.getSalary());
           

        }
    }//GEN-LAST:event_txtBaseSalaryFocusLost

    private void btnWriteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteFileActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("nhanvien.dat");
            OutputStreamWriter osw = new OutputStreamWriter(fos);
            BufferedWriter bw = new BufferedWriter(osw);
            String line = "";
            int i;
            for (i = 0; i < list.size(); i++) {
                
                line += list.get(i).getName() + "$";
                line += list.get(i).getBirthday() + "$";
                line += list.get(i).getAddress() + "$";
                line += list.get(i).getSex() + "$";
                line += list.get(i).getDepartment() + "$";
                line += list.get(i).getSalaryrate() + "$";
                line += list.get(i).getSeniority() + "$";
                line += list.get(i).getBasesalary() + "$";
                line += list.get(i).getSalary();
                bw.write(line);
                bw.newLine();
            }
            
            bw.close();
            fos.close();
            osw.close();
            JOptionPane.showMessageDialog(rootPane, "Lưu thành công danh sách Nhân viên");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnWriteFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReadFile;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnWriteFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane pnSalary;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBaseSalary;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalaryrRate;
    private javax.swing.JTextField txtSeniority;
    // End of variables declaration//GEN-END:variables
}
